
spring:
  datasource:
      url: jdbc:mysql://120.79.62.203:3306/dc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Zh@19970322
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.2.23
    port: 6379
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
logging:
  file: F:\blog\log\blog.log3
server:
  servlet:
    context-path: /dc
  port: 8088

